name: Upload to Google Drive
on: [workflow_dispatch] # This triggers the upload every time you push code

jobs:
  upload_to_drive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload File
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
          filename: 'path/to/your/file.apk' # Change this to the file you want to upload
          folderId: '1wJ4o-av372pRVUd7sS1YvYyZ-l0-38im' # Paste the ID from Phase 2
          overwrite: "false"
